services:
    nginx:
        container_name: fs-form-container
        image: fs-form:0.0.1
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - feedback-system-network

networks:
    feedback-system-network:
        external: true
